#page title
page_title                                : Luisa Moraes                             # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                            # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/br/app/birodigital/id1570370423                                         # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.biroapp                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
site_client_link                          : https://luisamoraes.biro.digital                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logobt.svg                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_logo                                  : assets/logobranco.svg                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Luisa Moraes                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Contrate advogados e acompanhe processos na palma da sua mão.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Luisa Moraes                                
your_link                                 : Biro.digital                    
your_city                                 : Belo Horizonte - MG                                
email_address                             : contato@luisamoraesadvogados.com.br
facebook_username                         : luisamoraesadvogados                                        
instagram_username                        : luisamoraes_advogados
twitter_username                          : 
github_username                           : 
youtube_username                          : UCF-g6BEByWXmeWe5DE5TVOw
linkedin_username                         : company/luisa-moraes-advogados



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Ambiente Online Seguro # New Feature Title
    description                           : Os seus dados pessoais estão seguros com a gente! Os mesmos serão tratados conforme a Lei Geral de Proteção de Dados e hipótese alguma repassados a terceiros. # New Feature Description
    fontawesome_icon_name                 : lock # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.
  
  - title                                 : Pagamento Seguro com Garantia # New Feature Title
    description                           : Todo o processo de pagamento conta com criptografia de ponta a ponta garantindo toda segurança do início ao fim. # New Feature Description
    fontawesome_icon_name                 : money-check-alt # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.
  
  - title                                 : Acompanhe seus processo sempre que quiser  # New Feature Title
    description                           : Após registrar a ação e realizar todas as etapas posteriores. Você consegue acompanhar seu processo sempre que quiser! # New Feature Description
    fontawesome_icon_name                 : thumbtack # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.
  
  - title                                 : Seja avisado quando houver um andamento no processo # New Feature Title
    description                           : Obtemos  transparência em todas as etapas da gestão de causas judiciais, por isso tendo qualquer andamento no processo você receberá uma notificação do app com as informações atualizadas. # New Feature Description
    fontawesome_icon_name                 : bell # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.
  
  - title                                 : Organize seus Documentos # New Feature Title
    description                           : Prepare e envie documentos referentes a causas judiciais com facilidade e garanta que seu processo será publicado com rigor dentro das conformidades acordadas pelo seu advogado. # New Feature Description
    fontawesome_icon_name                 : file-pdf # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.
  
  - title                                 : Advogados focados em sua especialidade # New Feature Title
    description                           : Com a Birô ,  advogados podem atuar focados em sua especialidade com zero preocupação sobre as questões administrativas.  # New Feature Description
    fontawesome_icon_name                 : user-tie # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/alternativeheaderimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.3

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#650F40"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#650F40"
feature_icons_background_color            : "#EAEBEF"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown